/**
 * MINT Data Catalog
 * API Documentation for MINT Data Catalog
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: danf@usc.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class InlineResponse200DatasetStandardVariables {
    'standardVariableId'?: string;
    'standardVariableName'?: string;
    'standardVariableUri'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "standardVariableId",
            "baseName": "standard_variable_id",
            "type": "string"
        },
        {
            "name": "standardVariableName",
            "baseName": "standard_variable_name",
            "type": "string"
        },
        {
            "name": "standardVariableUri",
            "baseName": "standard_variable_uri",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return InlineResponse200DatasetStandardVariables.attributeTypeMap;
    }
}

