/**
 * MINT Data Catalog
 * API Documentation for MINT Data Catalog
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: danf@usc.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { Resource } from './resource';

export class InlineObject8 {
    'resources'?: Array<Resource>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "resources",
            "baseName": "resources",
            "type": "Array<Resource>"
        }    ];

    static getAttributeTypeMap() {
        return InlineObject8.attributeTypeMap;
    }
}

