/**
 * MINT Data Catalog
 * API Documentation for MINT Data Catalog
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: danf@usc.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { InlineResponse2001DatasetVariables } from './inlineResponse2001DatasetVariables';

export class InlineResponse2001Dataset {
    'datasetId'?: string;
    'datasetName'?: string;
    'variables'?: Array<InlineResponse2001DatasetVariables>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "datasetId",
            "baseName": "dataset_id",
            "type": "string"
        },
        {
            "name": "datasetName",
            "baseName": "dataset_name",
            "type": "string"
        },
        {
            "name": "variables",
            "baseName": "variables",
            "type": "Array<InlineResponse2001DatasetVariables>"
        }    ];

    static getAttributeTypeMap() {
        return InlineResponse2001Dataset.attributeTypeMap;
    }
}

