/**
 * MINT Data Catalog
 * API Documentation for MINT Data Catalog
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: danf@usc.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { InlineResponse2004DatasetVariables } from './inlineResponse2004DatasetVariables';

export class InlineResponse2004Dataset {
    'datasetId'?: string;
    'datasetName'?: string;
    'datasetDescription'?: string;
    'datasetMetadata'?: object;
    'variables'?: Array<InlineResponse2004DatasetVariables>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "datasetId",
            "baseName": "dataset_id",
            "type": "string"
        },
        {
            "name": "datasetName",
            "baseName": "dataset_name",
            "type": "string"
        },
        {
            "name": "datasetDescription",
            "baseName": "dataset_description",
            "type": "string"
        },
        {
            "name": "datasetMetadata",
            "baseName": "dataset_metadata",
            "type": "object"
        },
        {
            "name": "variables",
            "baseName": "variables",
            "type": "Array<InlineResponse2004DatasetVariables>"
        }    ];

    static getAttributeTypeMap() {
        return InlineResponse2004Dataset.attributeTypeMap;
    }
}

