/**
 * MINT Data Catalog
 * API Documentation for MINT Data Catalog
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: danf@usc.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { Variable } from './variable';

export class InlineObject7 {
    'variables'?: Array<Variable>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "variables",
            "baseName": "variables",
            "type": "Array<Variable>"
        }    ];

    static getAttributeTypeMap() {
        return InlineObject7.attributeTypeMap;
    }
}

