/**
 * MINT Data Catalog
 * API Documentation for MINT Data Catalog
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: danf@usc.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class InlineResponse2001DatasetVariables {
    'variableId'?: string;
    'variableName'?: string;
    'variableMetadata'?: object;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "variableId",
            "baseName": "variable_id",
            "type": "string"
        },
        {
            "name": "variableName",
            "baseName": "variable_name",
            "type": "string"
        },
        {
            "name": "variableMetadata",
            "baseName": "variable_metadata",
            "type": "object"
        }    ];

    static getAttributeTypeMap() {
        return InlineResponse2001DatasetVariables.attributeTypeMap;
    }
}

