/**
 * MINT Data Catalog
 * API Documentation for MINT Data Catalog
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: danf@usc.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { InlineResponse200DatasetStandardVariables } from './inlineResponse200DatasetStandardVariables';

export class InlineResponse200Dataset {
    'datasetId'?: string;
    'datasetName'?: string;
    'standardVariables'?: Array<InlineResponse200DatasetStandardVariables>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "datasetId",
            "baseName": "dataset_id",
            "type": "string"
        },
        {
            "name": "datasetName",
            "baseName": "dataset_name",
            "type": "string"
        },
        {
            "name": "standardVariables",
            "baseName": "standard_variables",
            "type": "Array<InlineResponse200DatasetStandardVariables>"
        }    ];

    static getAttributeTypeMap() {
        return InlineResponse200Dataset.attributeTypeMap;
    }
}

