/**
 * MINT Data Catalog
 * API Documentation for MINT Data Catalog
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: danf@usc.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { InlineResponse2002DatasetResources } from './inlineResponse2002DatasetResources';

export class InlineResponse2002Dataset {
    'datasetId'?: string;
    'datasetName'?: string;
    'resources'?: Array<InlineResponse2002DatasetResources>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "datasetId",
            "baseName": "dataset_id",
            "type": "string"
        },
        {
            "name": "datasetName",
            "baseName": "dataset_name",
            "type": "string"
        },
        {
            "name": "resources",
            "baseName": "resources",
            "type": "Array<InlineResponse2002DatasetResources>"
        }    ];

    static getAttributeTypeMap() {
        return InlineResponse2002Dataset.attributeTypeMap;
    }
}

