/**
 * MINT Data Catalog
 * API Documentation for MINT Data Catalog
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: danf@usc.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class Resource {
    /**
    * Unique identifier
    */
    'recordId': string;
    /**
    * record_id of the dataset that this resource belongs to
    */
    'datasetId': string;
    /**
    * record_id of the entitity that created this resource
    */
    'provenanceId': string;
    /**
    * Display name/title of the resource
    */
    'name': string;
    'resourceType': Resource.ResourceTypeEnum;
    /**
    * direct download url for this resource
    */
    'dataUrl': string;
    'metadata'?: object;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "recordId",
            "baseName": "record_id",
            "type": "string"
        },
        {
            "name": "datasetId",
            "baseName": "dataset_id",
            "type": "string"
        },
        {
            "name": "provenanceId",
            "baseName": "provenance_id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "resourceType",
            "baseName": "resource_type",
            "type": "Resource.ResourceTypeEnum"
        },
        {
            "name": "dataUrl",
            "baseName": "data_url",
            "type": "string"
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "object"
        }    ];

    static getAttributeTypeMap() {
        return Resource.attributeTypeMap;
    }
}

export namespace Resource {
    export enum ResourceTypeEnum {
        GeoJSON = <any> 'GeoJSON',
        NetCDF = <any> 'NetCDF',
        CSV = <any> 'CSV',
        GeoTIFF = <any> 'GeoTIFF',
        JSON = <any> 'JSON',
        SHP = <any> 'SHP',
        TXT = <any> 'TXT',
        WriteInYourOwn = <any> '<Write-in your own>'
    }
}
