/**
 * MINT Data Catalog
 * API Documentation for MINT Data Catalog
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: danf@usc.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class StandardVariable {
    /**
    * Unique identifier
    */
    'recordId': string;
    /**
    * Display name/title/label of the standard variable
    */
    'name': string;
    /**
    * Name of the ontology under which this standard variable is defined
    */
    'ontology': string;
    /**
    * public URI that defines this standard variable
    */
    'uri': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "recordId",
            "baseName": "record_id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "ontology",
            "baseName": "ontology",
            "type": "string"
        },
        {
            "name": "uri",
            "baseName": "uri",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return StandardVariable.attributeTypeMap;
    }
}

