/* tslint:disable */
/* eslint-disable */
/**
 * MINT Data Catalog
 * API Documentation for MINT Data Catalog
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: danf@usc.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    InlineResponse200DatasetStandardVariables,
    InlineResponse200DatasetStandardVariablesFromJSON,
    InlineResponse200DatasetStandardVariablesFromJSONTyped,
    InlineResponse200DatasetStandardVariablesToJSON,
} from './';

/**
 * 
 * @export
 * @interface InlineResponse2004DatasetVariables
 */
export interface InlineResponse2004DatasetVariables {
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2004DatasetVariables
     */
    variableId?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2004DatasetVariables
     */
    variableName?: string;
    /**
     * 
     * @type {object}
     * @memberof InlineResponse2004DatasetVariables
     */
    variableMetadata?: object;
    /**
     * 
     * @type {Array<InlineResponse200DatasetStandardVariables>}
     * @memberof InlineResponse2004DatasetVariables
     */
    standardVariables?: Array<InlineResponse200DatasetStandardVariables>;
}

export function InlineResponse2004DatasetVariablesFromJSON(json: any): InlineResponse2004DatasetVariables {
    return InlineResponse2004DatasetVariablesFromJSONTyped(json, false);
}

export function InlineResponse2004DatasetVariablesFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse2004DatasetVariables {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'variableId': !exists(json, 'variable_id') ? undefined : json['variable_id'],
        'variableName': !exists(json, 'variable_name') ? undefined : json['variable_name'],
        'variableMetadata': !exists(json, 'variable_metadata') ? undefined : json['variable_metadata'],
        'standardVariables': !exists(json, 'standard_variables') ? undefined : ((json['standard_variables'] as Array<any>).map(InlineResponse200DatasetStandardVariablesFromJSON)),
    };
}

export function InlineResponse2004DatasetVariablesToJSON(value?: InlineResponse2004DatasetVariables | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'variable_id': value.variableId,
        'variable_name': value.variableName,
        'variable_metadata': value.variableMetadata,
        'standard_variables': value.standardVariables === undefined ? undefined : ((value.standardVariables as Array<any>).map(InlineResponse200DatasetStandardVariablesToJSON)),
    };
}


