/* tslint:disable */
/* eslint-disable */
/**
 * MINT Data Catalog
 * API Documentation for MINT Data Catalog
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: danf@usc.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InlineResponse2006Dataset
 */
export interface InlineResponse2006Dataset {
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2006Dataset
     */
    variableId?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2006Dataset
     */
    name?: string;
    /**
     * record_id of the dataset that this variable belongs to
     * @type {string}
     * @memberof InlineResponse2006Dataset
     */
    datasetId?: string;
    /**
     * 
     * @type {object}
     * @memberof InlineResponse2006Dataset
     */
    metadata?: object;
}

export function InlineResponse2006DatasetFromJSON(json: any): InlineResponse2006Dataset {
    return InlineResponse2006DatasetFromJSONTyped(json, false);
}

export function InlineResponse2006DatasetFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse2006Dataset {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'variableId': !exists(json, 'variable_id') ? undefined : json['variable_id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'datasetId': !exists(json, 'dataset_id') ? undefined : json['dataset_id'],
        'metadata': !exists(json, 'metadata') ? undefined : json['metadata'],
    };
}

export function InlineResponse2006DatasetToJSON(value?: InlineResponse2006Dataset | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'variable_id': value.variableId,
        'name': value.name,
        'dataset_id': value.datasetId,
        'metadata': value.metadata,
    };
}


