/* tslint:disable */
/* eslint-disable */
/**
 * MINT Data Catalog
 * API Documentation for MINT Data Catalog
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: danf@usc.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InlineResponse2005Dataset
 */
export interface InlineResponse2005Dataset {
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2005Dataset
     */
    resourceId?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2005Dataset
     */
    name?: string;
    /**
     * record_id of the dataset that this resource belongs to
     * @type {string}
     * @memberof InlineResponse2005Dataset
     */
    datasetId?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2005Dataset
     */
    resourceType?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2005Dataset
     */
    dataUrl?: string;
    /**
     * 
     * @type {object}
     * @memberof InlineResponse2005Dataset
     */
    metadata?: object;
    /**
     * 
     * @type {Date}
     * @memberof InlineResponse2005Dataset
     */
    createdAt?: Date;
}

export function InlineResponse2005DatasetFromJSON(json: any): InlineResponse2005Dataset {
    return InlineResponse2005DatasetFromJSONTyped(json, false);
}

export function InlineResponse2005DatasetFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse2005Dataset {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'resourceId': !exists(json, 'resource_id') ? undefined : json['resource_id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'datasetId': !exists(json, 'dataset_id') ? undefined : json['dataset_id'],
        'resourceType': !exists(json, 'resource_type') ? undefined : json['resource_type'],
        'dataUrl': !exists(json, 'data_url') ? undefined : json['data_url'],
        'metadata': !exists(json, 'metadata') ? undefined : json['metadata'],
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
    };
}

export function InlineResponse2005DatasetToJSON(value?: InlineResponse2005Dataset | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'resource_id': value.resourceId,
        'name': value.name,
        'dataset_id': value.datasetId,
        'resource_type': value.resourceType,
        'data_url': value.dataUrl,
        'metadata': value.metadata,
        'created_at': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
    };
}


