/* tslint:disable */
/* eslint-disable */
/**
 * MINT Data Catalog
 * API Documentation for MINT Data Catalog
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: danf@usc.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InlineResponse2001DatasetVariables
 */
export interface InlineResponse2001DatasetVariables {
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2001DatasetVariables
     */
    variableId?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2001DatasetVariables
     */
    variableName?: string;
    /**
     * 
     * @type {object}
     * @memberof InlineResponse2001DatasetVariables
     */
    variableMetadata?: object;
}

export function InlineResponse2001DatasetVariablesFromJSON(json: any): InlineResponse2001DatasetVariables {
    return InlineResponse2001DatasetVariablesFromJSONTyped(json, false);
}

export function InlineResponse2001DatasetVariablesFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse2001DatasetVariables {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'variableId': !exists(json, 'variable_id') ? undefined : json['variable_id'],
        'variableName': !exists(json, 'variable_name') ? undefined : json['variable_name'],
        'variableMetadata': !exists(json, 'variable_metadata') ? undefined : json['variable_metadata'],
    };
}

export function InlineResponse2001DatasetVariablesToJSON(value?: InlineResponse2001DatasetVariables | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'variable_id': value.variableId,
        'variable_name': value.variableName,
        'variable_metadata': value.variableMetadata,
    };
}


