/* tslint:disable */
/* eslint-disable */
/**
 * MINT Data Catalog
 * API Documentation for MINT Data Catalog
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: danf@usc.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InlineObject6
 */
export interface InlineObject6 {
    /**
     * 
     * @type {Array<string>}
     * @memberof InlineObject6
     */
    datasetNamesIn?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof InlineObject6
     */
    datasetIdsIn?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof InlineObject6
     */
    standardVariableIdsIn?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof InlineObject6
     */
    standardVariableNamesIn?: Array<string>;
}

export function InlineObject6FromJSON(json: any): InlineObject6 {
    return InlineObject6FromJSONTyped(json, false);
}

export function InlineObject6FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineObject6 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'datasetNamesIn': !exists(json, 'dataset_names__in') ? undefined : json['dataset_names__in'],
        'datasetIdsIn': !exists(json, 'dataset_ids__in') ? undefined : json['dataset_ids__in'],
        'standardVariableIdsIn': !exists(json, 'standard_variable_ids__in') ? undefined : json['standard_variable_ids__in'],
        'standardVariableNamesIn': !exists(json, 'standard_variable_names__in') ? undefined : json['standard_variable_names__in'],
    };
}

export function InlineObject6ToJSON(value?: InlineObject6 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'dataset_names__in': value.datasetNamesIn,
        'dataset_ids__in': value.datasetIdsIn,
        'standard_variable_ids__in': value.standardVariableIdsIn,
        'standard_variable_names__in': value.standardVariableNamesIn,
    };
}


