/* tslint:disable */
/* eslint-disable */
/**
 * MINT Data Catalog
 * API Documentation for MINT Data Catalog
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: danf@usc.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InlineResponse2002DatasetResources
 */
export interface InlineResponse2002DatasetResources {
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2002DatasetResources
     */
    resourceId?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2002DatasetResources
     */
    resourceName?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2002DatasetResources
     */
    resourceDataUrl?: string;
    /**
     * 
     * @type {Date}
     * @memberof InlineResponse2002DatasetResources
     */
    resourceCreatedAt?: Date;
}

export function InlineResponse2002DatasetResourcesFromJSON(json: any): InlineResponse2002DatasetResources {
    return InlineResponse2002DatasetResourcesFromJSONTyped(json, false);
}

export function InlineResponse2002DatasetResourcesFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse2002DatasetResources {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'resourceId': !exists(json, 'resource_id') ? undefined : json['resource_id'],
        'resourceName': !exists(json, 'resource_name') ? undefined : json['resource_name'],
        'resourceDataUrl': !exists(json, 'resource_data_url') ? undefined : json['resource_data_url'],
        'resourceCreatedAt': !exists(json, 'resource_created_at') ? undefined : (new Date(json['resource_created_at'])),
    };
}

export function InlineResponse2002DatasetResourcesToJSON(value?: InlineResponse2002DatasetResources | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'resource_id': value.resourceId,
        'resource_name': value.resourceName,
        'resource_data_url': value.resourceDataUrl,
        'resource_created_at': value.resourceCreatedAt === undefined ? undefined : (value.resourceCreatedAt.toISOString()),
    };
}


