/* tslint:disable */
/* eslint-disable */
/**
 * MINT Data Catalog
 * API Documentation for MINT Data Catalog
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: danf@usc.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InlineResponse200DatasetStandardVariables
 */
export interface InlineResponse200DatasetStandardVariables {
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200DatasetStandardVariables
     */
    standardVariableId?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200DatasetStandardVariables
     */
    standardVariableName?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200DatasetStandardVariables
     */
    standardVariableUri?: string;
}

export function InlineResponse200DatasetStandardVariablesFromJSON(json: any): InlineResponse200DatasetStandardVariables {
    return InlineResponse200DatasetStandardVariablesFromJSONTyped(json, false);
}

export function InlineResponse200DatasetStandardVariablesFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse200DatasetStandardVariables {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'standardVariableId': !exists(json, 'standard_variable_id') ? undefined : json['standard_variable_id'],
        'standardVariableName': !exists(json, 'standard_variable_name') ? undefined : json['standard_variable_name'],
        'standardVariableUri': !exists(json, 'standard_variable_uri') ? undefined : json['standard_variable_uri'],
    };
}

export function InlineResponse200DatasetStandardVariablesToJSON(value?: InlineResponse200DatasetStandardVariables | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'standard_variable_id': value.standardVariableId,
        'standard_variable_name': value.standardVariableName,
        'standard_variable_uri': value.standardVariableUri,
    };
}


