/* tslint:disable */
/* eslint-disable */
/**
 * MINT Data Catalog
 * API Documentation for MINT Data Catalog
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: danf@usc.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    InlineResponse2001DatasetVariables,
    InlineResponse2001DatasetVariablesFromJSON,
    InlineResponse2001DatasetVariablesFromJSONTyped,
    InlineResponse2001DatasetVariablesToJSON,
} from './';

/**
 * 
 * @export
 * @interface InlineResponse2001Dataset
 */
export interface InlineResponse2001Dataset {
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2001Dataset
     */
    datasetId?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2001Dataset
     */
    datasetName?: string;
    /**
     * 
     * @type {Array<InlineResponse2001DatasetVariables>}
     * @memberof InlineResponse2001Dataset
     */
    variables?: Array<InlineResponse2001DatasetVariables>;
}

export function InlineResponse2001DatasetFromJSON(json: any): InlineResponse2001Dataset {
    return InlineResponse2001DatasetFromJSONTyped(json, false);
}

export function InlineResponse2001DatasetFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse2001Dataset {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'datasetId': !exists(json, 'dataset_id') ? undefined : json['dataset_id'],
        'datasetName': !exists(json, 'dataset_name') ? undefined : json['dataset_name'],
        'variables': !exists(json, 'variables') ? undefined : ((json['variables'] as Array<any>).map(InlineResponse2001DatasetVariablesFromJSON)),
    };
}

export function InlineResponse2001DatasetToJSON(value?: InlineResponse2001Dataset | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'dataset_id': value.datasetId,
        'dataset_name': value.datasetName,
        'variables': value.variables === undefined ? undefined : ((value.variables as Array<any>).map(InlineResponse2001DatasetVariablesToJSON)),
    };
}


