/* tslint:disable */
/* eslint-disable */
/**
 * MINT Data Catalog
 * API Documentation for MINT Data Catalog
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: danf@usc.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    InlineResponse2004DatasetVariables,
    InlineResponse2004DatasetVariablesFromJSON,
    InlineResponse2004DatasetVariablesFromJSONTyped,
    InlineResponse2004DatasetVariablesToJSON,
} from './';

/**
 * 
 * @export
 * @interface InlineResponse2004Dataset
 */
export interface InlineResponse2004Dataset {
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2004Dataset
     */
    datasetId?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2004Dataset
     */
    datasetName?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2004Dataset
     */
    datasetDescription?: string;
    /**
     * 
     * @type {object}
     * @memberof InlineResponse2004Dataset
     */
    datasetMetadata?: object;
    /**
     * 
     * @type {Array<InlineResponse2004DatasetVariables>}
     * @memberof InlineResponse2004Dataset
     */
    variables?: Array<InlineResponse2004DatasetVariables>;
}

export function InlineResponse2004DatasetFromJSON(json: any): InlineResponse2004Dataset {
    return InlineResponse2004DatasetFromJSONTyped(json, false);
}

export function InlineResponse2004DatasetFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse2004Dataset {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'datasetId': !exists(json, 'dataset_id') ? undefined : json['dataset_id'],
        'datasetName': !exists(json, 'dataset_name') ? undefined : json['dataset_name'],
        'datasetDescription': !exists(json, 'dataset_description') ? undefined : json['dataset_description'],
        'datasetMetadata': !exists(json, 'dataset_metadata') ? undefined : json['dataset_metadata'],
        'variables': !exists(json, 'variables') ? undefined : ((json['variables'] as Array<any>).map(InlineResponse2004DatasetVariablesFromJSON)),
    };
}

export function InlineResponse2004DatasetToJSON(value?: InlineResponse2004Dataset | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'dataset_id': value.datasetId,
        'dataset_name': value.datasetName,
        'dataset_description': value.datasetDescription,
        'dataset_metadata': value.datasetMetadata,
        'variables': value.variables === undefined ? undefined : ((value.variables as Array<any>).map(InlineResponse2004DatasetVariablesToJSON)),
    };
}


