/* tslint:disable */
/* eslint-disable */
/**
 * MINT Data Catalog
 * API Documentation for MINT Data Catalog
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: danf@usc.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    InlineResponse2002DatasetResources,
    InlineResponse2002DatasetResourcesFromJSON,
    InlineResponse2002DatasetResourcesFromJSONTyped,
    InlineResponse2002DatasetResourcesToJSON,
} from './';

/**
 * 
 * @export
 * @interface InlineResponse2002Dataset
 */
export interface InlineResponse2002Dataset {
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2002Dataset
     */
    datasetId?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2002Dataset
     */
    datasetName?: string;
    /**
     * 
     * @type {Array<InlineResponse2002DatasetResources>}
     * @memberof InlineResponse2002Dataset
     */
    resources?: Array<InlineResponse2002DatasetResources>;
}

export function InlineResponse2002DatasetFromJSON(json: any): InlineResponse2002Dataset {
    return InlineResponse2002DatasetFromJSONTyped(json, false);
}

export function InlineResponse2002DatasetFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse2002Dataset {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'datasetId': !exists(json, 'dataset_id') ? undefined : json['dataset_id'],
        'datasetName': !exists(json, 'dataset_name') ? undefined : json['dataset_name'],
        'resources': !exists(json, 'resources') ? undefined : ((json['resources'] as Array<any>).map(InlineResponse2002DatasetResourcesFromJSON)),
    };
}

export function InlineResponse2002DatasetToJSON(value?: InlineResponse2002Dataset | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'dataset_id': value.datasetId,
        'dataset_name': value.datasetName,
        'resources': value.resources === undefined ? undefined : ((value.resources as Array<any>).map(InlineResponse2002DatasetResourcesToJSON)),
    };
}


