/* tslint:disable */
/* eslint-disable */
/**
 * MINT Data Catalog
 * API Documentation for MINT Data Catalog
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: danf@usc.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    InlineResponse200DatasetStandardVariables,
    InlineResponse200DatasetStandardVariablesFromJSON,
    InlineResponse200DatasetStandardVariablesFromJSONTyped,
    InlineResponse200DatasetStandardVariablesToJSON,
} from './';

/**
 * 
 * @export
 * @interface InlineResponse200Dataset
 */
export interface InlineResponse200Dataset {
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200Dataset
     */
    datasetId?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200Dataset
     */
    datasetName?: string;
    /**
     * 
     * @type {Array<InlineResponse200DatasetStandardVariables>}
     * @memberof InlineResponse200Dataset
     */
    standardVariables?: Array<InlineResponse200DatasetStandardVariables>;
}

export function InlineResponse200DatasetFromJSON(json: any): InlineResponse200Dataset {
    return InlineResponse200DatasetFromJSONTyped(json, false);
}

export function InlineResponse200DatasetFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse200Dataset {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'datasetId': !exists(json, 'dataset_id') ? undefined : json['dataset_id'],
        'datasetName': !exists(json, 'dataset_name') ? undefined : json['dataset_name'],
        'standardVariables': !exists(json, 'standard_variables') ? undefined : ((json['standard_variables'] as Array<any>).map(InlineResponse200DatasetStandardVariablesFromJSON)),
    };
}

export function InlineResponse200DatasetToJSON(value?: InlineResponse200Dataset | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'dataset_id': value.datasetId,
        'dataset_name': value.datasetName,
        'standard_variables': value.standardVariables === undefined ? undefined : ((value.standardVariables as Array<any>).map(InlineResponse200DatasetStandardVariablesToJSON)),
    };
}


