/* tslint:disable */
/* eslint-disable */
/**
 * MINT Data Catalog
 * API Documentation for MINT Data Catalog
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: danf@usc.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Provenance
 */
export interface Provenance {
    /**
     * Unique identifier
     * @type {string}
     * @memberof Provenance
     */
    recordId: string;
    /**
     * Name of the entity
     * @type {string}
     * @memberof Provenance
     */
    name: string;
}

export function ProvenanceFromJSON(json: any): Provenance {
    return ProvenanceFromJSONTyped(json, false);
}

export function ProvenanceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Provenance {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'recordId': json['record_id'],
        'name': json['name'],
    };
}

export function ProvenanceToJSON(value?: Provenance | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'record_id': value.recordId,
        'name': value.name,
    };
}


