/* tslint:disable */
/* eslint-disable */
/**
 * MINT Data Catalog
 * API Documentation for MINT Data Catalog
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: danf@usc.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StandardVariable
 */
export interface StandardVariable {
    /**
     * Unique identifier
     * @type {string}
     * @memberof StandardVariable
     */
    recordId: string;
    /**
     * Display name/title/label of the standard variable
     * @type {string}
     * @memberof StandardVariable
     */
    name: string;
    /**
     * Name of the ontology under which this standard variable is defined
     * @type {string}
     * @memberof StandardVariable
     */
    ontology: string;
    /**
     * public URI that defines this standard variable
     * @type {string}
     * @memberof StandardVariable
     */
    uri: string;
}

export function StandardVariableFromJSON(json: any): StandardVariable {
    return StandardVariableFromJSONTyped(json, false);
}

export function StandardVariableFromJSONTyped(json: any, ignoreDiscriminator: boolean): StandardVariable {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'recordId': json['record_id'],
        'name': json['name'],
        'ontology': json['ontology'],
        'uri': json['uri'],
    };
}

export function StandardVariableToJSON(value?: StandardVariable | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'record_id': value.recordId,
        'name': value.name,
        'ontology': value.ontology,
        'uri': value.uri,
    };
}


